MusicWorm/ViewModels/ResultViewModel.cs
using MusicWorm.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MusicWorm.ViewModels
{
    public class ResultViewModel
    {
        public string Name { get; set; }
        public PartialResult Result1 { get; set; }
        public PartialResult Result10 { get; set; }
        public PartialResult Result20 { get; set; }
        public PartialResult Result50 { get; set; }
        public PartialResult Result100 { get; set; }
    }
}

MusicWorm/Controllers/ExperimentController.cs
using Microsoft.AspNetCore.Mvc;
using MusicWorm.Data;
using MusicWorm.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MusicWorm.Controllers
{
    public class ExperimentController : Controller
    {
        private readonly IExperimentRepository _experimentRepository;

        public ExperimentController(IExperimentRepository experimentRepository)
        {
           _experimentRepository = experimentRepository;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult PrepareArtists()
        {
            _experimentRepository.PrepareArtists();
            return RedirectToAction(nameof(Index));
        }

        public IActionResult PrepareProducts()
        {
            _experimentRepository.PrepareProducts();
            return RedirectToAction(nameof(Index));
        }

        public IActionResult PrepareOrders()
        {
            _experimentRepository.PrepareOrders();
            return RedirectToAction(nameof(Index));
        }

        public IActionResult CreateProduct(int times)
        {
            var result = _experimentRepository.CreateProduct(times);
            return View(result);
        }

        public IActionResult AddToShoppingCart(int times)
        {
            var result = _experimentRepository.AddToShoppingCart(times);
            return View(result);
        }

        public IActionResult CreateOrder(int times)
        {
            var result = _experimentRepository.CreateOrder(times);
            return View(result);
        }

        public IActionResult GetOrderByNumber(int times)
        {
            var result = _experimentRepository.GetOrderByNumber(times);
            return View(result);
        }

        public IActionResult GetAllOrders(int times)
        {
            var result = _experimentRepository.GetAllOrders(times);
            return View(result);
        }

        public IActionResult Results()
        {
           //_experimentRepository.DeleteAllData();
            _experimentRepository.PrepareData();

            var results = new List<ResultViewModel>();

            results.Add(_experimentRepository.CreateProduct());
            results.Add(_experimentRepository.AddToShoppingCart());
            results.Add(_experimentRepository.CreateOrder());
            results.Add(_experimentRepository.GetOrderByNumber());
            results.Add(_experimentRepository.GetAllOrders());

            return View(results);
        }
    }
}

MusicWorm/Views/Experiment/AddToShoppingCart.cshtml
@model PartialResult

<div class="text-center">
    <h1 class="display-4">Experiment here.</h1>
    <p>Experiment results here.</p>

    <table class="table table-bordered table-striped">
        <thead>
            <tr>
                <th>Time</th>
                <th>Deviation</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>@Model.Time.ToString("0.000")</td>
                <td>@Model.Deviation.ToString("0.000")</td>

            </tr>
        </tbody>
    </table>

</div>

MusicWorm/Views/Experiment/CreateOrder.cshtml
@model PartialResult

<div class="text-center">
    <h1 class="display-4">Experiment here.</h1>
    <p>Experiment results here.</p>

    <table class="table table-bordered table-striped">
        <thead>
            <tr>
                <th>Time</th>
                <th>Deviation</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>@Model.Time.ToString("0.000")</td>
                <td>@Model.Deviation.ToString("0.000")</td>

            </tr>
        </tbody>
    </table>

</div>

MusicWorm/Views/Experiment/CreateProduct.cshtml
@model PartialResult

<div class="text-center">
    <h1 class="display-4">Experiment here.</h1>
    <p>Experiment results here.</p>

    <table class="table table-bordered table-striped">
        <thead>
            <tr>
                <th>Time</th>
                <th>Deviation</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>@Model.Time.ToString("0.000")</td>
                <td>@Model.Deviation.ToString("0.000")</td>

            </tr>
        </tbody>
    </table>

</div>

MusicWorm/Views/Experiment/GetAllOrders.cshtml
@model PartialResult

<div class="text-center">
    <h1 class="display-4">Experiment here.</h1>
    <p>Experiment results here.</p>

    <table class="table table-bordered table-striped">
        <thead>
            <tr>
                <th>Time</th>
                <th>Deviation</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>@Model.Time.ToString("0.000")</td>
                <td>@Model.Deviation.ToString("0.000")</td>

            </tr>
        </tbody>
    </table>

</div>

MusicWorm/Views/Experiment/GetOrderByNumber.cshtml
@model PartialResult

<div class="text-center">
    <h1 class="display-4">Experiment here.</h1>
    <p>Experiment results here.</p>

    <table class="table table-bordered table-striped">
        <thead>
            <tr>
                <th>Time</th>
                <th>Deviation</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>@Model.Time.ToString("0.000")</td>
                <td>@Model.Deviation.ToString("0.000")</td>

            </tr>
        </tbody>
    </table>

</div>

MusicWorm/Views/Experiment/Index.cshtml
@{
    ViewData["Title"] = "Experiment Page";
}

<div class="text-center">
    <h1 class="display-4">Experiment here.</h1>
    <p>Experiment here.</p>
    <a class="btn btn-danger" asp-controller="Experiment" asp-action="Results">Begin experiment</a>

    <div>
        <h2>Prepare data</h2>
        <a class="btn btn-success" asp-controller="Experiment" asp-action="PrepareArtists">PrepareArtists</a>
        <a class="btn btn-success" asp-controller="Experiment" asp-action="PrepareProducts">PrepareProducts</a>
        <a class="btn btn-success" asp-controller="Experiment" asp-action="PrepareOrders">PrepareOrders</a>
    </div>

    <div>
        <h2>CreateProduct</h2>
        <a class="btn btn-primary" asp-controller="Experiment" asp-action="CreateProduct" asp-route-times="1">1</a>
        <a class="btn btn-primary" asp-controller="Experiment" asp-action="CreateProduct" asp-route-times="10">10</a>
        <a class="btn btn-primary" asp-controller="Experiment" asp-action="CreateProduct" asp-route-times="20">20</a>
        <a class="btn btn-primary" asp-controller="Experiment" asp-action="CreateProduct" asp-route-times="50">50</a>
        <a class="btn btn-primary" asp-controller="Experiment" asp-action="CreateProduct" asp-route-times="100">100</a>
    </div>

    <div>
        <h2>AddToShoppingCart</h2>
        <a class="btn btn-primary" asp-controller="Experiment" asp-action="AddToShoppingCart" asp-route-times="1">1</a>
        <a class="btn btn-primary" asp-controller="Experiment" asp-action="AddToShoppingCart" asp-route-times="10">10</a>
        <a class="btn btn-primary" asp-controller="Experiment" asp-action="AddToShoppingCart" asp-route-times="20">20</a>
        <a class="btn btn-primary" asp-controller="Experiment" asp-action="AddToShoppingCart" asp-route-times="50">50</a>
        <a class="btn btn-primary" asp-controller="Experiment" asp-action="AddToShoppingCart" asp-route-times="100">100</a>
    </div>

    <div>
        <h2>CreateOrder</h2>
        <a class="btn btn-primary" asp-controller="Experiment" asp-action="CreateOrder" asp-route-times="1">1</a>
        <a class="btn btn-primary" asp-controller="Experiment" asp-action="CreateOrder" asp-route-times="10">10</a>
        <a class="btn btn-primary" asp-controller="Experiment" asp-action="CreateOrder" asp-route-times="20">20</a>
        <a class="btn btn-primary" asp-controller="Experiment" asp-action="CreateOrder" asp-route-times="50">50</a>
        <a class="btn btn-primary" asp-controller="Experiment" asp-action="CreateOrder" asp-route-times="100">100</a>
    </div>

    <div>
        <h2>GetOrderbyNumber</h2>
        <a class="btn btn-primary" asp-controller="Experiment" asp-action="GetOrderbyNumber" asp-route-times="1">1</a>
        <a class="btn btn-primary" asp-controller="Experiment" asp-action="GetOrderbyNumber" asp-route-times="10">10</a>
        <a class="btn btn-primary" asp-controller="Experiment" asp-action="GetOrderbyNumber" asp-route-times="20">20</a>
        <a class="btn btn-primary" asp-controller="Experiment" asp-action="GetOrderbyNumber" asp-route-times="50">50</a>
        <a class="btn btn-primary" asp-controller="Experiment" asp-action="GetOrderbyNumber" asp-route-times="100">100</a>
    </div>

    <div>
        <h2>GetAllOrders</h2>
        <a class="btn btn-primary" asp-controller="Experiment" asp-action="GetAllOrders" asp-route-times="1">1</a>
        <a class="btn btn-primary" asp-controller="Experiment" asp-action="GetAllOrders" asp-route-times="10">10</a>
        <a class="btn btn-primary" asp-controller="Experiment" asp-action="GetAllOrders" asp-route-times="20">20</a>
        <a class="btn btn-primary" asp-controller="Experiment" asp-action="GetAllOrders" asp-route-times="50">50</a>
        <a class="btn btn-primary" asp-controller="Experiment" asp-action="GetAllOrders" asp-route-times="100">100</a>
    </div>

</div>

MusicWorm/Views/Experiment/Results.cshtml
@model IEnumerable<ResultViewModel>
@{
    ViewData["Title"] = "Experiment Page";
}

<div class="text-center">
    <h1 class="display-4">Experiment here.</h1>
    <p>Experiment results here.</p>

    <table class="table table-bordered table-striped">
        <thead>
            <tr>
                <th>Test name</th>
                <th>1</th>
                <th>10</th>
                <th>20</th>
                <th>50</th>
                <th>100</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
            <tr>
                <td>@item.Name</td>
                <td>@item.Result1.Time.ToString("0.000") ± @item.Result1.Deviation.ToString("0.000")</td>
                <td>@item.Result10.Time.ToString("0.000") ± @item.Result10.Deviation.ToString("0.000")</td>
                <td>@item.Result20.Time.ToString("0.000") ± @item.Result20.Deviation.ToString("0.000")</td>
                <td>@item.Result50.Time.ToString("0.000") ± @item.Result50.Deviation.ToString("0.000")</td>
                <td>@item.Result100.Time.ToString("0.000") ± @item.Result100.Deviation.ToString("0.000")</td>
            </tr>
            }
        </tbody>
    </table>

</div>